---
- name: Install Java 11
  become: true
  apt:
    update_cache: yes
    name: openjdk-11-jdk 
    state: present

- name: Correct alternatives to change default java version
  alternatives:
    name: java
    path: /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java
  